export default actionTypes = {

    GET_LOCATIONS: 'GET_LOCATIONS',
    GET_LOCATIONS_SUCCESS:'GET_LOCATIONS_SUCCESS',
    GET_LOCATIONS_FAIL: 'GET_LOCATIONS_FAIL',

    USER_RESPONSE_PUSH : 'USER_RESPONSE_PUSH',
    USER_RESPONSE_PUSH_SUCCESS: 'USER_RESPONSE_PUSH_SUCCESS',
    USER_RESPONSE_PUSH_FAIL: 'USER_RESPONSE_PUSH_FAIL',

    SAVE_LOCATION: 'SAVE_LOCATION',








}