export default actionTypes = {

    GET_LOCATIONS: 'GET_LOCATIONS',
    GET_LOCATIONS_SUCCESS:'GET_LOCATIONS_SUCCESS',
    GET_LOCATIONS_FAIL: 'GET_LOCATIONS_FAIL',

    USER_RESPONSE_PUSH : 'USER_RESPONSE_PUSH',
    USER_RESPONSE_PUSH_SUCCESS: 'USER_RESPONSE_PUSH_SUCCESS',
    USER_RESPONSE_PUSH_FAIL: 'USER_RESPONSE_PUSH_FAIL',

    SAVE_LOCATION: 'SAVE_LOCATION',
    
    GET_TIME: 'GET_TIME',
    GET_TIME_SUCCESS: 'GET_TIME_SUCCESS',
    GET_TIME_FAIL: 'GET_TIME_FAIL',

    MAKE_ISERROR_TRUE: 'MAKE_ISERROR_FALSE',








}